version: "3"

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    hostname: server
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - yarn:/usr/local/share/.cache/yarn/v2
  arena:
    image: weijing329/bee-queue-arena:v2.5.0
    depends_on:
      - redis
    ports:
      - "4567:4567"
    volumes:
      - ./set.json:/opt/arena/src/server/config/index.json
  redis:
    image: redis:4.0.11-alpine
    read_only: true
    # ports:
    #   - "6380:6380"
    volumes:
      - redis:/data
    user: redis

volumes:
  # db:
  redis:
  yarn:
